/*
 * jitter_source.ino -- second oscillator for the PHarvard entropy experiment.
 *
 * Emits a square wave on pin D9, generated by Timer1 in hardware. The FPGA
 * counts its own clock cycles between edges; the VARIANCE of that count is the
 * accumulated jitter between the two oscillators, and that number decides
 * whether a two-oscillator entropy source is viable here at all.
 *
 * WHY THE HARDWARE TIMER AND NOT digitalWrite() IN A LOOP.
 * This is the whole point of the sketch. A software-toggled pin carries the
 * jitter of interrupt latency, loop timing and the compiler -- none of which is
 * the crystal's phase noise. Timer1 driving OC1A directly means every edge is a
 * pure integer division of the oscillator, so what the FPGA measures is the
 * oscillator and nothing else. Measuring software jitter and calling it
 * physical entropy is the classic way to get this wrong.
 *
 * WHY SLOW, AND NOT THE RAW 16 MHz CLOCK.
 * Jitter accumulates as a random walk: over N cycles it grows like sqrt(N).
 * Dividing to 1 kHz means every edge carries the accumulated noise of 16,000
 * crystal cycles, roughly 126x more than a single cycle. It also makes the
 * resistor divider harmless -- at 16 MHz the divider plus the FPGA's pin
 * capacitance is a real low-pass, at 1 kHz it is nothing.
 *
 * TUNING. If the FPGA sees zero variance, the jitter is below its 480 ns
 * resolution: go slower. Each step down multiplies the accumulated jitter by
 * sqrt(10). Change OUT_HZ below and reflash.
 *
 *   1000 Hz  -> start here
 *    100 Hz
 *     10 Hz  -> if this still shows nothing, the pair is too stable to use
 *
 * WIRING: D9 -> 1k -> [node] -> FPGA pin 113
 *                     [node] -> 2k -> GND
 *         Arduino GND -> FPGA GND        (mandatory, no shared ground no data)
 *
 * The divider is there because this board's logic is 5 V and the MachXO2's
 * inputs are not 5 V tolerant. Measure a pin with a multimeter before trusting
 * that; if the board turns out to be 3.3 V, wire D9 straight across.
 *
 * Made with my soul - Swately <3
 */

const unsigned long F_CPU_HZ = 16000000UL;   // this board's crystal
const unsigned long OUT_HZ   = 1000UL;       // <-- the knob

void setup() {
    // D9 is PB1, which is Timer1's OC1A output pin on an Uno-class board.
    DDRB |= (1 << PB1);

    // Stop the timer while it is reconfigured.
    TCCR1A = 0;
    TCCR1B = 0;
    TCNT1  = 0;

    // Pick the smallest prescaler that keeps the compare value inside 16 bits,
    // because a smaller prescaler divides the crystal less coarsely.
    const unsigned int prescalers[] = {1, 8, 64, 256, 1024};
    const uint8_t      cs_bits[]    = {
        (1 << CS10),                 // /1
        (1 << CS11),                 // /8
        (1 << CS11) | (1 << CS10),   // /64
        (1 << CS12),                 // /256
        (1 << CS12) | (1 << CS10)    // /1024
    };

    unsigned long top = 0;
    uint8_t       cs  = cs_bits[4];
    for (uint8_t i = 0; i < 5; i++) {
        // toggle rate = F_CPU / (2 * prescaler * (1 + OCR1A))
        unsigned long t = F_CPU_HZ / (2UL * prescalers[i] * OUT_HZ);
        if (t >= 1 && t <= 65536UL) {
            top = t - 1;
            cs  = cs_bits[i];
            break;
        }
    }

    OCR1A  = (unsigned int) top;
    TCCR1A = (1 << COM1A0);              // toggle OC1A on compare match
    TCCR1B = (1 << WGM12) | cs;          // CTC on OCR1A, start the clock

    // The serial port is only here so the board announces itself; it plays no
    // part in generating the signal.
    Serial.begin(115200);
    Serial.print(F("jitter_source: D9 square wave at "));
    Serial.print(OUT_HZ);
    Serial.println(F(" Hz, generated by Timer1 in hardware"));
}

void loop() {
    // Deliberately empty. Anything running here would add supply noise and
    // could couple into the very oscillator being measured.
}
